# -*-coding:utf-8-*-
import torch

DEFAULT_CONFIG = {
    'lr': 0.015,
    'epochs': 1000,
    'lr_decay': 0.05,
    'l2_rate': 1.0e-8,
    'momentum': 0.,
    'batch_size': 64,
    'dropout': 0.5,
    'max_norm': 3.0,
    'static': True,
    'non_static': False,
    'multichannel': False,
    'embedding_dim': 300,
    'position_embedding_dim': 20,
    'hidden_dim': 300,
    'bidirectional': True,
    'filter_num': 100,
    'filter_sizes': [3, 4, 5],
    'num_layers': 2,
    'pad_index': 1,
    'vector_path': '',
    'tag_num': 0,
    'vocabulary_size': 0,
    'word_vocab': None,
    'tag_vocab': None,
    'save_path': '../saves',
    'pretrained_path': '../pretrained',
    'pretrained_name': 'sgns.zhihu.word',
    'max_patience': 10,
    'log_interval': 1,
    'save_dir': '../joint_snapshot',
    'save_best': True,
    'device': torch.cuda.device_count() - 1,
    'cuda': torch.cuda.is_available(),
    'snapshot': '../joint_snapshot/joint_model.pkl',
    'snapshot_args': '../joint_snapshot/joint_args.pkl'
}
